### ISSUE TITLE
Data file style

### ISSUE THREAD

**Issue by zj023** [LLNL/tdmtpy#1]
Can you share the corresponding file data style? Because there is no corresponding data, it is difficult to understand the logical relationship of the code. zj_023@126.com,THANKS

**Comment by nurcankahyaersolak** [comment]
Can you share the corresponding file data style? Because there is no corresponding data, it is difficult to understand the logical relationship of the code. zj_023@126.com,THANKS

**Comment by ahchiang** [comment]
A new release is coming up soon and will include more documentation and examples.

**Comment by ahchiang** [comment]
please check out the wiki for more documentation.
