### ISSUE TITLE
Inversion with ZNE components

### ISSUE THREAD

**Issue by saeedsltm** [LLNL/tdmtpy#4]
Dear @ahchiang, sometimes we need to use ZNE components instead of ZRT due to issues with some specific component. It would be nice if you could put an example regarding that (may also including "tensor" type green functions).

**Comment by ahchiang** [comment]
Thanks for the suggestion, in the meantime you can run the notebook example without rotating the data to ZRT. For tensor type Green's functions you can try the examples in the synthetic folder, tensor format is used when you need to compute 3D synthetics.

**Comment by saeedsltm** [comment]
Thanks @ahchiang
