### ISSUE TITLE
mttime for microearthquake moment tensor 

### ISSUE THREAD

**Issue by dickyaz** [LLNL/tdmtpy#5]
Greetings @ahchiang, hope you are doing well.

I've been trying the notebook and it's went well, except some error in plotting appeared but I'm trying to solving it.
I'm wondering that could we use mttime for solving microearthquake mt?
Let say the eq in depth of 2-5 km with freq signal in range of 20 - 50 Hz, the epi distance in range 1 - 10 km, the magnitude below 2 Mw. Thank you.

Best Regards,
Dicky

**Comment by ahchiang** [comment]
Hello Dicky, not 20-50 Hz at these distances, maybe up to 2 Hertz if you have a suitable velocity model.

**Comment by ahchiang** [comment]
Hello Dicky, not 20-50 Hz at these distances, maybe up to 2 Hertz if you have a suitable velocity model.
