### ISSUE TITLE
Question about the inversion with a pure isotropic source

### ISSUE THREAD

**Issue by wangzb0329** [LLNL/tdmtpy#7]
Dear @ahchiang, I'm interested in the inversions for moment tensors of non-double-couple sources. In your paper(Moment tensor analysis for NKT events), you assume a pure isotropic source in the inversion.  How can I modify the notebook files to achieve this result? It would be nice if you could put an example.
Thank you

**Comment by ahchiang** [comment]
Hello, if you are referring to the 2018 paper the inversions were done assuming the full MT and not pure ISO. I typically do a grid search over a range of isotropic moments to find a pure ISO source. Hope this helps.

**Comment by wangzb0329** [comment]
Thank you very much for your reply.
